require "bundler"
Bundler::GemHelper.install_tasks

require "rake/testtask"
Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.test_files = FileList["test/test_*.rb"]
end

begin
  require "rubocop/rake_task"
  RuboCop::RakeTask.new
rescue LoadError
  desc "Run RuboCop"
  task :rubocop do
    warn "Rubocop is disabled"
  end
end

Dir.glob("tasks/*.rake").each { |r| import r }

task release: ["completion:zsh", "completion:bash"]
task default: %i[test rubocop]
